### ISSUE TITLE
Adding document name to ref and doc tags

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#100]
@cjmayo, @Condo-Colin Making this an issue instead of a thread in the PR since when you close it, it doesn't make sense to keep a conversation going there. I don't fully understand autosectionlabel_prefix_document. Right now, every title is a link which for the first "make github" command you will get a lot of "duplicate label" warnings. But they go away until some other action happens. Not sure what that is. From the quick read, it looks like autosection label puts a prefix on the front of every title automatically? Or do you have to do it? Ex: hardware:how to, software:how to. Perhaps it is manualy, which is why you added this:

"If you agree I can probably add a commit here that adds the document to these :doc: and :ref: targets (not something I want to do if it isn't going to be used."

I think we should use it and make that a standard just like we have for which character underline is use for which heading, how we use "note", etc.

**Comment by cjmayo** [comment]
I thought a PR, #101, would be a better way to illustrate autosectionlabel_prefix_document than writing even more words.

**Comment by Condo-Colin** [comment]
I'm still learning the technical conglomerations of GitHub/VCS, so you guys work out what you want to do, and I can help type it up.
