### ISSUE TITLE
Add Bluetooth serial PC link info

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#102]
KC using a HC-05/HC-06 Bluetooth module on Serial0 {Tx0 Rx0} Mega+ WiFi shield [Makerfab8266] CS connected Bluetooth to a PC JMRI for Operations, and a second USB cable to a Mega+Wifi Combo CS to the same PC JMRI for Programming Station and Testing.  The Serial Bluetooth connection works over 25ft+ as well as the serial USB.

You can also directly connect to the first CS with either a WiFi WiThrottle App and with a Bluetooth capable WiThrottle App.
The HC-05 would be more flexible with the ability to  be either a master or a slave.

**Comment by peteGSX** [comment]
This has already been done with the HC-05/06 page.
