### ISSUE TITLE
Note general Serial pin allocations

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#107]
KC:
USB Serial0 comm for Firmware updates, and Mega+ESP WiFi Combo Board defaults to Serial3 Tx Rx for WiFi, Leaving Serial1 & Serial2 for User options.
Plus the shortest wire from a MakerFab WiFI Shield and Mega WiFi TxRx would also be the Serial3 pins.

**Comment by peteGSX** [comment]
I think the new pin/vpin page should hopefully cover this sufficiently.
