### ISSUE TITLE
Broken/over-long external links in pages.

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#113]
- more long Amazon links here:
https://dcc-ex.com/reference/tools/serial-monitor.html#otg-cable

- broken image links
https://dcc-ex.com/advanced-setup/wifi-config.html#ap-mode

**Comment by cjmayo** [comment]
>     * broken image links
>       https://dcc-ex.com/advanced-setup/wifi-config.html#ap-mode

I can only see a link to `WiFi_softap_mode.png` in the "AP Mode" section, that one seems to be working?

**Comment by cjmayo** [comment]
Amazon links (and others) fixed in  #126.

**Comment by peteGSX** [comment]
Validated this was all done.
