### ISSUE TITLE
Add info on Mega+WiFi board?

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#114]
The Mega+WiFi unit is an Arduino Mega clone design with an ESP8266 WiFi chip on one board. Since they are hard-wired together, they needed to have a way for you to be able to use both devices separately. So the TXRX01/03 switch needs to be there so you can choose which serial port on the Mega, the ESP connects to. We want 3. This is the equivalent of you using 2 jumpers on a discrete ESP-8266 board and connecting them to serial 3 on a regular Mega.
The dip switches are there because you need to program 2 different devices and you only have one USB port. They could have used jumpers, but that would be even more confusing and have dangling wires. So you flip the switches one way so that the USB port on the Mega is rewired on the board to connect to the ESP instead. You then have to switch it back so that you are talking to the Mega. Once you program the ESP chip, you don't have to mess with the switches again unless you need to update the ESP.

**Comment by pmantoine** [comment]
Probably need a nice stylised diagram of how the DIP switches make either the ESP8266 or Mega visible to the USB port?

**Comment by peteGSX** [comment]
Going to leave the existing info as-is. Given the recent build quality issues experienced, we shouldn't be encouraging any more of these in the wild.
