### ISSUE TITLE
Add turnout activation pulse info

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#117]
From Chris:

To do pin pulse turnouts with exrail do this:

To create a turnout on pins 20,21 use a PIN_TURNOUT with an id of 20 but a pin of 0. 
This will appear as a turnout to throttles etc but will not change pin 0 because the hal protects that.

Then you can use ON event handlers like this 

ONCLOSE (20)
SET(20) DELAY(250) RESET(20) DONE

ONTHROW(20)
SET(21) DELAY(250) RESET(21)
DONE

From Haba:

Start with a delay of say 25.
But if this is a 298N, you first need to set DIR and then pulse the enable.

ONCLOSE(20)
RESET(DIR)
SET(ENABLE) DELAY(25) RESET(ENABLE)
DONE

ONTHROW(20)
SET(DIR)
SET(ENABLE) DELAY(25) RESET(ENABLE)
DONE

For example:

#define KATOTURNOUT(t,p1,p2) \
ONCLOSE(t) \
RESET(p1) \
SET(p2)DELAY(25)RESET(p2) \
DONE \
ONTHROW(t) \
RESET(p2) \
SET(p1)DELAY(25)RESET(p1) \
DONE

and use as
KATOTURNOUT(20,33,35)
KATOTURNOUT(21,37,39)

@UKBloke (AKA Chris) Correct???

**Comment by Condo-Colin** [comment]
From peteGSX:

With the L293D chip, if enable is always high, the output pins will always be on, so not good for the Rokuhan/Kato turnouts.
The way to drive them is to set the direction pins, then set enable high then low to provide the pulse.
The L298 is what that example’s for which is a different kettle of fish.
Use MCP23017s on I²C to control the  L393Ds.

**Comment by peteGSX** [comment]
I'm wrapping this in to my tips and tricks page.

**Comment by peteGSX** [comment]
This was actually closed by https://github.com/DCC-EX/dcc-ex.github.io/pull/189.
