### ISSUE TITLE
Add simple servo connection examples

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#118]
These are the kind of support questions we need examples and details for, especially with regard to JMRI integration.

"Where do I define my servo?"

"Show me an example sketch on a single servo for a turnout used in conjunction with jmri and a PCA9685."

"How would you calibrate the throw for a servo?
I currently am using little wicket sketch for servos.
But am curious as to the dccex automation programming."

**Comment by Condo-Colin** [comment]
From Chris:

Bear in mind that we have multiple ways of handling stuff because of the backward compatibility drag with DCC++ and the addition of directly connected throttle capability. 
I would suggest that we continue to push the one BEST approach and relegate the others to a "not recommended but available for backward compatibility...." type of category.

IMHO The most fully featured method of defining Turnouts (not things pretending to be turnouts just because JMRI doesn't understand!)  is to use the EXRAIL macros. (TURNOUT, SERVO_TURNOUT, PIN_TURNOUT) 

This is because:
a)  Its the only place where we can reasonably include turnout descriptions to be shown on throttle buttons without burning RAM. 
b) One can also use EXRAIL to manage complex pin pulsing etc for turnout technologies that are not hard-coded features of the CS., including external bus systems. 

=============================
In order to answer the single-servo question above I would take the following basic approach:
1) Mount servo and wire to PCA9685 but NOT physically connected to turnout.
2) Use <D SERVO> command to find the best position numbers for that servo at that turnout.
3) Add a SERVO_TURNOUT macro to your EXRAIL script, giving an id, the numbers you have discovered and the required speed parameters.
4) Test with <T id 0/1> commands.
5) Physically connect servo to turnout.

**Comment by Condo-Colin** [comment]
From Ash:
The setup might be different for JMRI.  It has the Configure Base Station screen.  It can simplify getting things installed on the layout, without having to ever reload a DCC++EX sketch. 

The request was:   example sketch on a single servo for a turnout used in conjunction with jmri and a PCA 9685

![unknown-13.png](https://user-images.githubusercontent.com/85348898/151097059-c1ee9f8c-897d-4147-9a79-80b051acb61a.png)

**Comment by peteGSX** [comment]
This is covered off with our new turnout section, although we don't have JMRI defined in there as we're not the JMRI support team...
