### ISSUE TITLE
Add <l> (L) command into for loco control?

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#120]
Details:
l : lower case letter "L"
CABID: The loco number which is controlled
SLOTID: Ignore this.
SPEED: Speed in DCC encoded format. 0 stop, 1 emergency stop, 2 to 127 speed steps, 128 stop, 129 emergency stop, 130-255 speed steps. 128 to 255 is the other direction compared to 0 to 127
FUNCTIONS: You need to think binary.

**Comment by liamoreilly** [comment]
The documentation for the `<t ...>` command can also be updated (as it is the same area of the [docs](https://dcc-ex.com/reference/software/command-reference.html#engine-decoder-cab-operation-commands)) to reflect that it is possible to leave out the depreciated 'REGISTER' parameter (this then prevents the depreciated `<t ...>` response message from being sent, so only the newer `<l ...>` message is sent).

**Comment by peteGSX** [comment]
Fixing this in https://github.com/DCC-EX/dcc-ex.github.io/issues/201

**Comment by peteGSX** [comment]
Hey @liamoreilly we'll leave the <t ....> doco as-is as it is still actively used in other scenarios, but I do note that the REGISTER part is already commented as deprecated, and simply providing a 1 or similar is all that's required.

The <T ...> return is still actively used elsewhere as well at the moment.

I will say thanks for commenting on this issue and providing some feedback though, that's always helpful.

Will close this off as part of https://github.com/DCC-EX/dcc-ex.github.io/issues/201
