### ISSUE TITLE
Add an EX-RAIL tips and tricks page

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#162]
It'd be handy to have a page dedicated page to capture the various tips and tricks resulting from questions in Discord, especially to get Chris' ideas out from his head in a way that he doesn't have to keep repeating himself and can get on with what he needs to.

Here's some copy/pasted notes from various conversations where Chris' key tip of thinking from the engineer's or train's perspective when designing automation sequences:

Yes you're right on the money....
It's the difference between looking at a layout from above and trying to coordinate everything... and driving a route from the drivers perspective. 
Using point sensors has always seemed to me to be so much more powerful than block occupancy...   "I know where I'm going and when I get to sensor 123 I know i must reserve blocks 6 and 9"

It always struck me that block occupancy was not a great place to start ... because I came across so many automation things it didn't help with.
Reversing into a siding for example.  Just because a block is empty doesn't mean you can drive into it because sometimes a block will physically cross over 1 or more others or you may have a blocked exit with a train coming the other way.
I think, for the most part, point sensors seem more useable for automation and block sensors more suitable for mimic panels.
(especially if you think automation from the drivers perspective)
Now I do have some nags about point sensors... it just seems such a pain that one needs so much wire and cheap IR sensors suffer from sunlight etc. Now what would be so super would be a tiny sensor that looked like the real thing and sat between the tracks, ran on track power, and used bluetooth or something to broadcast its events to a central unit. Alternatively the video-cam sensing would be really cool!

What about a script that uses an enter and exit sensor but you need to know which direction the train is going? Is it as simple as just having 2 sequences? AT sensor 1 do something and stop doing it AFTER sensor 2 triggers and resets. But if you go the other way, now sensor 2 triggers the action and you wait for 1 to trigger or to trigger and then reset to stop the action?

UKBloke (AKA Chris) — 02/18/2022
That's a problem because you are not in a position to enter a section like that just because it's empty... because a train coming the other way in the next block will be blocking yoyr exit... 
To handle a situation like this you need to reserve well ahead ... ie before you block the exit  for a train coming he other way. 
This means you will know which way things are happening in the block in question BEFORE any train can enter it.
This is easy to do if your scripts run from the drivers perspective... but a PITA if you run from the signalman perspective.

What I mean is that its POSSIBLE to create a sequence to take any train from somewhere to somewhere and then send any particular loco on that journey... BUT in reality we don't tend to model a real railway with 20 identical trains running up and down a main line... we model a variety of trains and each one has its characteristics like sounds or realistic speeds, or loco direction or train length or rolling-stock types. 

So rather than creating generic routes, think from the trains perspective like .....
  This  is a passenger train with carriage lights and a diesel sound loco with a XXX decoder which requires switching on with F4 and has a fancy station announcement on F19. 
It will sit in siding A quietly until xxx happens (may be a random wait) and then it will warm up the engine and move to platform B where it will stop, turn on the carriage lights one by one and make an announcement. 60 seconds later it will set off at speed blah blah to station C where it will stop for 30 seconds and than contiunue.... At some point (random or switch) it will switch off the lights and return to its siding and shut down.

**Comment by FrightRisk** [comment]
It's funny. I have a word doc with some of those and about 2 years worth of other stuff. Some of this needs to go into the pages they discuss, for example ex-rail comments should go into ex-rail. That can either be a "tips" callout (line our "notes" and "warning" items) or maybe a page. What ideas do you have?

**Comment by peteGSX** [comment]
@FrightRisk Fred, care to share what's in that Word doc? Happy for these ideas just to get wrapped in to existing pages if that's the preference for sure.

The main ideas I had were centred around the tips I've seen Chris have to repeat on numerous occasions in Discord to get people thinking from the engineer/driver perspective rather than the overall layout perspective, which I've captured in my first comment on this issue. I haven't quite figured out how to get that a bit more succinct yet though! The main driver (haha) is to free Chris up to get on with what he needs/wants to rather than have to answer the same questions over and over.

Outside of that, there's a reminder on reading doco (yeah possibly too obvious!), then linear to address/subaddress conversion, defining your own EX-RAIL commands/macros, and further clarification on having multiple files included from myAutomation.h.

The current draft I'm working on is in this branch: https://github.com/DCC-EX/dcc-ex.github.io/tree/peteGSX-EX-RAIL-tips

**Comment by FrightRisk** [comment]
Well, all of it needs organizing and cleanup. I have a bunch of bullets in word and when I have time I put them in the project page. We may move that to the new projects format. I need to learn about that too.  Knock one task down and 2 more pop up. Perhaps you and @Condo-Colin can help with seeing what overlap there is on the "dev" repo and the "DCC++EX Development" repos. I don't know if we need two anymore. The repos are linked to issues though and I need to refresh myself on how I set that up. It's nice to have the issues linked to a Kanban and when you check an item off the list. Can you guys take a look at the github docs on how the new projects work? 

Let me know if both of you can see the dev and DCC++EX projects on this page: https://github.com/orgs/DCC-EX/projects

**Comment by peteGSX** [comment]
More than happy to do so! I can see both those projects, have had a quick peruse of the new project documentation, and will have a look with Colin this week to see what we can organise.
