### ISSUE TITLE
Update SERVO_TURNOUT to clarify using text rather than integers for the profile

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#163]
Defining a SERVO_TURNOUT requires the profile to be specified as text as defined in IODevice.h rather than an integer, which is a bit ambiguous in the documentation and could use some clarification.

**Comment by FrightRisk** [comment]
Do you have a sentence or paragraph to insert somewhere? Trying to spread the work around ;)

**Comment by peteGSX** [comment]
Oh ooops I meant to assign this to myself! I need to revisit but the EX-RAIL bit was a bit ambiguous and the reference I initially found mentioned integers whereas text is required. I'll find, fix, and do a pull request for this one.

**Comment by peteGSX** [comment]
PR raised: https://github.com/DCC-EX/dcc-ex.github.io/pull/170
