### ISSUE TITLE
Add warnings and instruction for using Ethernet

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#19]
We are using networking primarily for allowing direct connection from a Throttle to the Command Station to avoid the need for any other software. Some people in the past connected the CS to JMRI via the network instead of using a USB Cable from a Raspberry Pi or some other computer.  Address the issues in doing this.

**Comment by Condo-Colin** [comment]
Does this also include WiFi connections? Just network connections in general?
Has this been covered on the website?
