### ISSUE TITLE
Correct API documentation

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#201]
Need to provide an API update based on feedback received:

"I came across an error in the API doc yesterday. It states that function commands have no answer from the API, but in fact I get one: 

Out: <f 910 128>

Reply from API: <l 910 0 128 0>l"

**Comment by peteGSX** [comment]
Found this here: https://dcc-ex.com/reference/software/command-reference.html

RETURNS: NONE
CAB Functions do not have a Return

@Asbelos has there been an update here since the documentation was written so that CAB functions do indeed now have a return? What are the various returned numbers for? I can see the cab ID (910) and what would be F28 (128), but the two zeroes are a mystery to me.

**Comment by peteGSX** [comment]
From Hans:

Based on the data I get it is <l SLOT DCCADDR DIR/SPEED FCTSTATUS>
DIR/SPEED is 8 bits with bit 7 the direction indicator
FCTSTATUS is the bit patten of all the functions with light in bit 0, then F1 in bit 1, F2 in bit 2, and so on.

**Comment by peteGSX** [comment]
Correction: <l DCC SLOT DIR/SPEED FCTSTATUS>

**Comment by Asbelos** [comment]
Strictly speaking, this is not a response, its a broadcast of status and can arise when any throttle  is changed by someone else. Thus there is no guarantee that you will get the message if your throttle command changed nothing, nor that the next <l> message you receive will be from your most recent throttle command.
