### ISSUE TITLE
Investigate Newer RTD Theme

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#217]
We're still using a Beta RTD theme for the website, need to investigate running a later version.

**Comment by cjmayo** [comment]
As far as I am aware the remaining issue is that the mobile top navigation bar is not visible:
https://github.com/readthedocs/sphinx_rtd_theme/issues/1285

It can be worked around by adding some CSS instead of the conf.py html_theme_options setting.

**Comment by peteGSX** [comment]
Cool, thanks for the pointer! I hadn't done any research yet. I did update my own personal project's pages to use it and will check that out there, although that's a very vanilla install of the theme and I've not touched any CSS as yet.

**Comment by peteGSX** [comment]
This was done in the website refresh.
