### ISSUE TITLE
Decoder Feedback: 

### ISSUE THREAD

**Issue by EinMariusImNetz** [DCC-EX/dcc-ex.github.io#265]
* Brand: Märklin
* Model: m83
* Type: ACC
* Firmware: default
* Connector: screw terminal
* ACK Settings:
* Rating: 2/3
* Comments:

**Comment by peteGSX** [comment]
Thanks @EinMariusImNetz ! Do you have any comments on why you rated this 2/3? Were any issues encountered etc.?

**Comment by peteGSX** [comment]
Captured feedback.
