### ISSUE TITLE
Correct </> example output

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#273]
Need to correct the example output for `</>` as this is not quite right:

`<* EXRAIL STATUS
ID=0,PC=12,LOCO=0 ,SPEED=0F
ID=1,PC=12,LOCO=18 ,SPEED=50F *>`

This output indicates two threads are running the same script statement (PC=12) which actually demonstrates there's an issue with myAutomation.h.

**Comment by Asbelos** [comment]
It's not a problem to have two tasks running at thexsame pc= if that's what you intended.. its just rarel.

**Comment by peteGSX** [comment]
Ah right, this was taken from feedback in Discord that suggested this was an error, so if it's possible then we'll leave it be.
