### ISSUE TITLE
[Documentation Update]: Throttle developer page enhancements

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#297]

**Comment by FrightRisk** [comment]
RETURNS: <l CAB SLOT SPEED/DIR FUNC>

Where:

CAB is the loco DCC address/CAB ID.

SLOT is the slot assignment for the CAB.

SPEED/DIR is the 8 bit speed byte:

Bit 7 provides the direction (1 = Fwd, 0 = Rev).

Bits 0 to 6 provide the speed (0 - 128).

FUNC is the bit pattern for the functions that are set.

**Comment by FrightRisk** [comment]
This is from a conversation with Chris and Harald. Chris thought the placement of that above text was awkward. He said it was ok here: https://dcc-ex.com/developer-reference/tech-reference.html (which is not there anymore). He found it after functions, not throttle in the command reference. He thought it was included elsewhere but not easy to search for and so pointed to that link. He also hates the variables in caps when we also have keywords in caps.

Harald said, "Throttle devs need to understand that power can be 3 states: on, off and unknown. And then we have not started to talk about districts in error condition."

**Comment by peteGSX** [comment]
Ok, so, the one thing I believe we're missing for throttle developers is clarity on the broadcasts which I talked to Chris about the other week, so I can add those to the developer page (https://dcc-ex.com/reference/developers/tech-reference.html).

I've already fixed the command reference page today to ensure that parameters/variables are in lower case, leaving upper case for OPCODES only.

Not sure how to deal with the power states other than to make it obvious (also on the developer page) that three states are possible.

**Comment by peteGSX** [comment]
This is Chris' summary of the broadcasts:

The first and most important thing is to say that a throttle MUST accept and ignore anything it doesn't understand. 
The other broadcasts are power `<p ..>`  turnout throw/close `<H ..>`  and defined sensor changes `<q/Q..>`
