### ISSUE TITLE
Add a 'how to compile section'

### ISSUE THREAD

**Issue by grbba** [DCC-EX/dcc-ex.github.io#3]
A people may use either Platform IO and VSC or PlatformIO on Atom or the Arduino IDE it would be very helpful to have a section on how to build the CommandStation from within each of those. Maybe VSC/PlatformIO and Arduino IDE would be sufficient though.

**Comment by Condo-Colin** [comment]
Has this been sufficiently covered on the webpage?

**Comment by pmantoine** [comment]
It's been covered with the Arduino IDE. There's no mention of how to compile DCC++EX using PlatformIO. The dev section here: https://dcc-ex.com/contributing/development.html is empty!

**Comment by peteGSX** [comment]
I don't think we need to repeat PlatformIO documentation in here... we outline to install PlatformIO with VSCode, that should be sufficient.
