### ISSUE TITLE
Update PCA9685 section about using "servo" to configure a "signal head"

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#335]
User went on a long search, so this will help someone else. He is using signal heads that use a "command anode". He changed the code so that the SET / RESET values are reversed.

IODevice::configureServo(104,0,4095,PCA9685::NoPowerOff);
SETUP("<Z 104 104 0>");

He tried another solution by NeilMck — 11/08/2021. 

https://discord.com/channels/713189617066836079/780769297542676502/907362416906600488

Neil suggested  using a turnout command: <T 1 SERVO 100 4095 0 128>  and also suggested using this: IODevice::configureServo(100, 4095, 0, 128);

The user could not get this to work, which is not to say it doesn't work, just that he gave up and got it to work as described here.  How can we make this easy to understand and where should it go?

**Comment by Ash-4** [comment]
Previous info  https://github.com/DCC-EX/Support-Planning/issues/459#issuecomment-1221039983
-- and the info was mostly from Chris:
https://discord.com/channels/713189617066836079/873794422993727568/917861294491729960

Solution by NeilMck worked without issue.   Tested using a single LED connected to PWM/GND of PCA9685.
(No need for IODevice::configureServo if using this method.)

<* PARSING:T 108 SERVO 108 4095 0 128 *>
<O>
<* PARSING:T 108 1 *>
<H 108 1>
<* PARSING:T 108 0 *>
<H 108 0>
