### ISSUE TITLE
[Documentation Update]: Sensor pins on Arduino Mega

### ISSUE THREAD

**Issue by 4x4falcon** [DCC-EX/dcc-ex.github.io#390]
### Documentation details

Sensors directly connected to Arduino Mega.
Looking at here:

https://dcc-ex.com/ex-rail/creating-elements.html?highlight=sensors#adding-sensors

shows that a sensor can be added to pins 22, 23, 24...62.

To me this shows that I can add a sensor to the analog pins A0-A8 (D54-D62) which would block the current sensors for the motor board.

Maybe this should be 22, 23, 24...53 which are all the digital pins on the dual row connector at the end of the mega.  These are not used by anything else in DCC-EX.

### Page with issues

https://dcc-ex.com/ex-rail/creating-elements.html

**Comment by habazut** [comment]
I think the range ends at 49 if you have stacked an ethernet (not Wifi) shield. Then you can start at D60 (A6) and up again which normally is unused. It is not so easy to write a guide including all free pins because "it depends".

**Comment by 4x4falcon** [comment]
Maybe better to show what pins DCC-EX uses depending on the configuration attached.
eg:

------------------------------------------------------------------------------------------------------------------------
D0 D1 RX0/TX0                                  USB connection

D2 - D13 motor shields                       Depends on motor shield, some may not be in use.

D14 D15 TX3/RX3 for Serial 3            #define SERIAL3_COMMANDS in config.h  or WIFI  (optional)
D16 D17 TX2/RX2 for Serial 2            #define SERIAL2_COMMANDS in config.h  or WIFI  (optional)
D18 D19 TX1/RX1 for Serial 1            #define SERIAL1_COMMANDS in config.h  or WIFI  (optional)

D20 D21 SDA/SCL for I2C                  I2C connection

D22 - D49                                            Not normally used

D50 - D53                                            Arduino Ethernet Shield  (optional)

A0 A1  current sense for motor shield

A2 - A15  (D56 - D69)                          Not normally used

--------------------------------------------------------------------------------------------------------------------------------------

This is not comprehensive and just what I've found scanning through the current documentation and source in 30 mins but to me gives a minimum use list of the pins.

My main concern with the current documentation is that the 22,23,24...62 is not correct and some users may think that they can use D54 and D55 as sensor inputs or outputs and therefore not have current sensing.
