### ISSUE TITLE
[Documentation Update]: Refine sensor and output settings

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#409]
### Documentation details

Add something like this from Ash. We need a more clear explanation of how JMRI integrates with EX-CS: EXRAIL automation does not need sensors and vpin outputs pre-defined, as it uses the pin numbers.  So there is an added setup step if you use JMRI.

JMRI sends the T, S, and Z commands at startup and populates its turnouts and sensors tables.  You can then update the tables and save them.  Reload the tables when you start JMRI, and JMRI will merge in new additions.

If you have removed or modified things in DCC-EX, you will need to do some editing of the JMRI tables.

**Comment by Kcsmith0708** [comment]
The comment 'EXRAIL Automation does not need sensors and vpin outputs pre-defined, as it uses the pin numbers. " may need clarification.

The problem with not defining things like outputs <z n n 1> ahead of time in mySetup.h is if you configured a DFPlayer mini microSD card MP3 Player in myHal.h, and you want to use send commands from serial monitor like <Z> or <Z 1001 1> to Start a sound file, It will not work and respond < X >.    So we need some Virtual vpins to be defined in mySetup.h.

It's more than just using it to help automatically populate JMRI Tools Table> etc..

But the good news is that all your individual defined <Z n n 1> Outputs will select-able and testable in JMRI Tool Tables > Turnouts as [Throw{on}], [Close{off}] buttons.
