### ISSUE TITLE
[Documentation Update]: LOW - Fix sensor IDs in diagram to match EX-RAIL example

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#419]
### Documentation details

The example diagrams need to have sensor IDs updated to match the examples on the EX-RAIL page.

### Page with issues

https://dcc-ex.com/ex-rail/examples.html

**Comment by sbegnaud** [comment]
I had some time, fixed the Diagram. Hope you can use it?
![Example_7b_diagram](https://user-images.githubusercontent.com/54481017/229972871-6abfc126-7bde-49f8-b4f9-f013bbfed1d9.png)

**Comment by peteGSX** [comment]
Yes perfect, thanks so much @sbegnaud !

I've updated and the website is rebuilding now.
