### ISSUE TITLE
[Documentation Update]: Teensy info required

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#424]
### Documentation details

Someone with knowledge of the Teensy will need to cover this off.

LOW - Hardware - Add pinouts and motor shield wiring diagrams

### Page with issues

https://dcc-ex.com/reference/hardware/microcontrollers/teensy.html

**Comment by pmantoine** [comment]
User Uli on Discord is our only user of Teensy at present I think. He has a Teensy 4.1 model, and is running the pre-v5.0 devel tree. He's also running EX-RAIL, which by doing so helped find a bug. You might hit him up for a diagram or three? Maybe a pic?
