### ISSUE TITLE
[Documentation Update]: IBT_2 Fritzing and current sense info required

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#426]
### Documentation details

Someone familiar with the IBT_2 motor driver will need to provide further info and a Fritzing diagram here.

LOW - Hardware - Fritzing image of 2 ibt 2 boards here

LOW - Hardware - Add help or point to a section for external current sense boards

### Page with issues

https://dcc-ex.com/reference/hardware/motorboards/IBT_2-motor-board-setup.html

**Comment by Wreckingball7** [comment]
![BTS_7960_dual_bb](https://github.com/DCC-EX/dcc-ex.github.io/assets/67566877/ebe2547f-3750-4445-b178-73f2269d7427)

**Comment by Wreckingball7** [comment]
One of my first FRitzing tries.  Hope that it is usable to the group/

**Comment by probonopd** [comment]
> LOW - Hardware - Add help or point to a section for external current sense boards

How to do this? Thanks.

**Comment by Ash-4** [comment]
This is the circuit I use with the IBT_2 motor boards for current sensing.
![connShield_24_zener_circuit2](https://github.com/DCC-EX/dcc-ex.github.io/assets/81280775/3dde4f4f-31f8-46c7-8ccf-ee644355384e)

The external current sensing boards will work for overcurrent sensing, but may not be as useful for reading CVs on the programming track.  This is one I have tried.  https://www.pololu.com/product/4042
It is used on the +V of the track power supply, and would sense the current on both tracks, requiring that MAIN track is off when programming track is used.

For further discussion, please use the motor shields channel on the discord server, or the open a ticket channel on discord.
https://discord.gg/y2sB4Fp
