### ISSUE TITLE
[Documentation Update]: Add new info to EX-RAIL section

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#499]
### Documentation details

Edit something like this where appropriate from KC Smith:

I have use C++ on Arduino's and Python/Jython on JMRI software to build Automation sequences. I now use EXRAIL instead because:
1) It's TenX Time Easier and more flexible than the other two options
2) I reduce the number of Uno and Nano accessory boards needed to do the same tasks on the layout by using the DCC-EX Command Station and  embedded EXRAIL instead.
3) I can create Automation, Routes & Sequence scripts With EXRAIL on the Command Station and still access them from JMRI PanelPro and DecoderPro GUI buttons with a simple sendDCCmessage.py script pointer that passes them to the EXRAIL scripts on the Command Station.  So I don't have to rewrite the script in Jython/Python
4) EXRAIL id 10X times Easier to learn and use and is more Flexible then the other methods.

**Comment by msirois** [comment]
I second the motion.

**Comment by peteGSX** [comment]
Captured
