### ISSUE TITLE
Bad text on home page

### ISSUE THREAD

**Issue by Asbelos** [DCC-EX/dcc-ex.github.io#5]
1. 1 or 2 byte loco address not 2,4
2. Whats new list not sub indented 
3. No railcom cutout

**Comment by Condo-Colin** [comment]
Was item 1. addressed? Is 2 & 4 correct? Or should it read 1 & 2 byte??

**Comment by peteGSX** [comment]
Fixing this in https://github.com/DCC-EX/dcc-ex.github.io/issues/201
