### ISSUE TITLE
[Documentation Update]: Add solenoid/coil turnout driver info using ULN2003

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#501]
### Documentation details

@momfertje has shared that a ULN2003 stepper driver (easily obtained on eBay etc.) can be used relatively simply to drive solenoid/coil turnouts. We should add an EX-RAIL example of how this can be done, along with the provided image.

![Turnout_GPIO_uln2003_board_bb](https://user-images.githubusercontent.com/97784652/205514883-8d8b7b30-3698-44aa-9b2e-7c6465599589.jpg)

**Comment by ghost** [comment]
When it will be used, I can make a version with the new logo (no ++)

**Comment by ghost** [comment]
Strike that, after supporting someone on Discord, my opinion on using the ULN2003 stepper board has changed. The boards support 5-12V which is (even when stretched to 15V) for most solenoid (coil) based switching machines (snappers) too low. It is also hard to parallel the ports (on this board) to double the current to drive more demanding snappers.

Nevertheless the board can be nice to test outputs, just by reading the LEDS go on/off and of course as driver for the stepper motor.

The ULN2x03 series can handle the job when carefully utilized (and with parallel wired ports) , but not as example for the documentation.
