### ISSUE TITLE
[Documentation Update]: duinoNode support to be added.

### ISSUE THREAD

**Issue by Asbelos** [DCC-EX/dcc-ex.github.io#519]
### Documentation details

devel branch now has support for duinoNodes
raw info on how to use is in the devel Release_Notes/duinoNodes.md

For hardware info see https://beaglebay.com/duinogear/ldg-duinonodes/

**Comment by peteGSX** [comment]
Forgot to close this, done: https://dcc-ex.com/ex-commandstation/development/duinonodes.html
