### ISSUE TITLE
[Documentation Update]: Add explanations of the types of turnouts

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#529]
### Documentation details

We show how to configure a servo turnout, a vpin tunout, etc. but do not explain what they are. We should have at least a basic description and a link to any connection/configuration details that may be elsewhere

### Page with issues

https://dcc-ex.com/reference/software/command-reference.html#defining-setting-up-a-turnout

**Comment by peteGSX** [comment]
This should be covered as part of https://github.com/DCC-EX/dcc-ex.github.io/issues/502
