### ISSUE TITLE
[Documentation Update]: missing parameter in sample

### ISSUE THREAD

**Issue by Asbelos** [DCC-EX/dcc-ex.github.io#540]
### Documentation details

SERVO_TURNOUT has missing profile parameter in sample code. 

### Page with issues

https://dcc-ex.com/ex-rail/tips.html#realistic-turnout-sequences

**Comment by peteGSX** [comment]
This has been fixed as part of the front page/intro shuffle, will close this off once a PR is raised and merged for that.
