### ISSUE TITLE
[Documentation Update]: Add detail to the HAL / I2C page

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#555]
### Documentation details

Updates made by Neil: On the non-blocking driver, timeout monitoring now works as intended, retries are performed on failed operations, and there's a check on the SDA/SCL lines to see whether they're shorted to ground.  Retries are done on Wire, and timeouts where the Wire interface allows.

Current testing:
1) shorting the SDA and SCL lines (separately) to GND and checking that a warning is raised following a reset, all I2C devices are reported as failed (timed out) and otherwise the CS continues running normally.
2) Forcing timeouts on long packets and checking that the devices using shorter packets aren't affected.
If you've got a logic analyser, then other tests are possible (e.g. inspecting the I2C signal directly). 
The modified code is on branch devel-nmck.

**Comment by peteGSX** [comment]
@pmantoine this probably fits with the V5 release doco https://github.com/DCC-EX/dcc-ex.github.io/issues/665

I will close this one, but you should see a link for reference now.
