### ISSUE TITLE
[Documentation Update]: Add help for using a mux with a sub bus to the I2C page

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#580]
### Documentation details

This from a post by Paul:

When using a multiplexor (mux), here's how you configure things, like multiple displays on SubBus addresses in v4.2.2x:
//  HALDisplay<OLED>::create(0, {SubBus_0, 0x3d}, 128, 64);
// HALDisplay<OLED>::create(0, {SubBus_1, 0x3c}, 128, 64);
// HALDisplay<OLED>::create(1, {SubBus_5, 0x3c}, 128, 64);
// HALDisplay<LiquidCrystal_I2C>::create(0, {SubBus_1, 0x27}, 16, 2);

The default config of the 2 default MCP23017s in IODevice.h is:
  // Predefine two MCP23017 module 0x20/0x21
  // Allocates 32 pins 164-195
  MCP23017::create(164, 16, 0x20);
  MCP23017::create(180, 16, 0x21);

But you this will have to be added:
MCP23017::create(341, 16, {SubBus_1, 0x20});

**Comment by pmantoine** [comment]
Whilst the initial I2C mux page is done... there is a limitation not mentioned in the current doco, that I discovered today (21/8/2023):

For any device of the same address that you wish to use... you may **not** have one of those devices on the main I2C bus itself.

All devices of the same address (e.g. OLEDs on 0x3C) must be on **separate** sub-buses of ANY of the muxes, and none of the OLEDs on 0x3C can be on the main bus itself.

So, say you want 2x OLEDs... you cannot put one on the main I2C bus, and another on a sub-bus. Both must reside on separate sub-buses. This is a limitation of the way muxes work... once a sub-bus is enabled on the mux, the mux is effectively transparent to the main bus... so an 0x3C OLED on the main bus will then collide with the one on the sub-bus.

...now... I need to think of a clearer way of stating this... <sigh>

**Comment by Kcsmith0708** [comment]
Important Distinction for OLED displays
There are at least two diffferent OLED four wire Pinout and Address formats.
1)  pinouts with (VCC GND SCL SDA) with addresses 0x3c & 0x3d
2)  pinouts with (GND VIN SCK SDA) with addresses 0x7a & 0x7b
Make sure the VCC & GND, or GND & VIN wires are aligned correctly or the OLED will immediatly overheat and may damage the device.
