### ISSUE TITLE
[Documentation Update]: Update link to EX-MotorShield8874 on GitHub

### ISSUE THREAD

**Issue by felicevittoria** [DCC-EX/dcc-ex.github.io#647]
### Documentation details

When clicking on the link it's redirecting to itself.  Here is the current link:
https://dcc-ex.com/reference/hardware/motorboards/ex-motor-shield-8874.html#dcc-ex-ex-motorshield8874-reva

### Page with issues

https://dcc-ex.com/reference/hardware/motorboards/ex-motor-shield-8874.html

**Comment by pmantoine** [comment]
Thanks for noticing that Felice! We had moved the repo up one level and broken the link.
