### ISSUE TITLE
[Documentation Update]: Update myAutomation.h example

### ISSUE THREAD

**Issue by felicevittoria** [DCC-EX/dcc-ex.github.io#648]
### Documentation details

Currently the example for myAutomation.h shows the following:

void halSetup() {
  ...
  HAL(EXIOExpander, 800, 18, 0x65)
  HAL(EXIOExpander, 820, 16, 0x66)
}

This needs to be corrected to the following:

HAL(EXIOExpander, 800, 18, 0x65)
HAL(EXIOExpander, 820, 16, 0x66)

### Page with issues

https://dcc-ex.com/ex-ioexpander/overview.html

**Comment by peteGSX** [comment]
Looks like this was fixed already.
