### ISSUE TITLE
[Documentation Update]: Wrong link in Mega+Wifi instructions

### ISSUE THREAD

**Issue by nathankellenicki** [DCC-EX/dcc-ex.github.io#654]
### Documentation details

Hello hello - I set up a Mega+WiFi today following the instructions here - https://dcc-ex.com/reference/hardware/microcontrollers/wifi-mega.html

Which all worked fine, thanks! However at the end of flashing part d ("part d. Flash the firmware" > "Run the Flasher Tool") it says "Skip ahead to c. Set the switches on your Mega for flashing".  Except we already did that before part d. 🙂 I think it should say "Skip ahead to e. Set the switches for run/sketch mode"

### Page with issues

https://dcc-ex.com/reference/hardware/microcontrollers/wifi-mega.html

**Comment by FrightRisk** [comment]
Thank you Nathan, excellent work!

**Comment by pmantoine** [comment]
Thanks Nathan... fixed the reference 🥇
