### ISSUE TITLE
Exrail sample errot

### ISSUE THREAD

**Issue by Asbelos** [DCC-EX/dcc-ex.github.io#661]
### Documentation details

I think I found a tiny hiccup in the documentation for ex-rail in the Tips and Techniques page ( https://dcc-ex.com/ex-rail/tips.html ):
in the example for Realistic turnout sequences -when closing the virtual turnout- you are switching both MainlineSignal and ShuntingSignal to GREEN for 12,5 secs and in the middle of this time the turnout is actually moving- I guess you should swap the lines for the signals, so it does look something like this:
```ONCLOSE(9101)                                // When closing the virtual turnout:
RED(ShuntingSignal)                          // Set a red signal.
DELAY(5000)                                  // Wait for the signalman to move to the turnout lever.
CLOSE(101)                                   // Close the real turnout.
DELAY(7500)                                  // Wait again for the signalman to move to the other signal lever.
GREEN(MainlineSignal)                        // Set a green signal.
DONE```

### Page with issues

https://dcc-ex.com/ex-rail/tips.html

**Comment by peteGSX** [comment]
Fixed now so it makes sense.
