### ISSUE TITLE
v5 release: TrackManager

### ISSUE THREAD

**Issue by pmantoine** [DCC-EX/dcc-ex.github.io#663]
TrackManager is new to release v5.0

- currently documented in Under Development: DCC-EX TrackManager (https://dcc-ex.com/under-development/track-manager.html)
- needs moving to... "EX-COMMANDSTATION ADD-ONS"  as for EX-RAIL?
- needs breaking out into sub-pages in a hierarchy much like EX-RAIL?
- any of the EX-RAIL scripts need mentioning in the EX-RAIL doco?
- any updates/changes not yet covered that will appear?

**Comment by peteGSX** [comment]
For release, just the page shuffle will suffice, doco is pretty good as-is, further EXRAIL updates etc. can come with time although we should validate the EXRAIL pages include TrackManager commands.

**Comment by peteGSX** [comment]
Missing TrackManager commands.
