### ISSUE TITLE
v5 release: duinoNodes

### ISSUE THREAD

**Issue by pmantoine** [DCC-EX/dcc-ex.github.io#664]
Currently documented in "Under Development: Lew's Duino Gear duinoNodes (https://dcc-ex.com/under-development/duinonodes.html)

Needs moving to... "EX-COMMANDSTATION ADD-ONS", or perhaps under "Adding and Controlling Accessories"?

Any updates needed before publishing?

**Comment by peteGSX** [comment]
Actually this is already done, nothing to do here.
