### ISSUE TITLE
v5.0 release: News Announcement

### ISSUE THREAD

**Issue by pmantoine** [DCC-EX/dcc-ex.github.io#666]
Previous News included Breaking Changes announcement here:

https://dcc-ex.com/news/posts/20230327.html
 
Need to update this to a full release announcement, including:

New <JG> and <JI> commands for multi-track gauges such as current sensing (v4.2.20)

Static IP address now configurable for Ethernet shields (v4.2.24)

SAMD21 had a bug in EX-RAIL due to memory alignment, this likely improves 32-bit support for various microcontrollers (v4.2.25)

Improved stability/reliability of the EX‑IOExpander device driver (v4.2.26) and bug fix for analogue inputs (v4.2.34)

Updated the DFPlayer code to cope with a new variant of the popular sound board seen in the wild, and mods to the HCRS04 ultrasonic driver so it uses less CPU loop time (v4.2.28)

Various LCD bug fixes (latest in v4.2.29)

Add <z> direct I/O pin manipulation command (v4.2.35)

Add new “FLAGS” device to the HAL to communicate Vpin changes outside of EX‑RAIL to software such as [JMRI](https://dcc-ex.com/reference/glossary.html) (v4.2.37)

Also need to cover specifically:

- Trackmanager
- Multiple displays
- I2C improvements, including error recovery, support for multiplexors/multiple buses
- EX-IOExpander support (alpha)
- EX-FastClock support
- EX-Turntable
- Re-iterate about the new EX-Installer

**Comment by peteGSX** [comment]
This is generally good, one final item is to correct the date for when we actually do the release and publish the news.
