### ISSUE TITLE
Native DCC-EX network connection via USB on PC/RPi

### ISSUE THREAD

**Issue by pmantoine** [DCC-EX/dcc-ex.github.io#730]
Harald noted you can use socat to create a network port for direct DCC-EX native protocol access via the USB port on a CS connected to a PC or RPi:

You can, if you can run socat instead of jmri on your computer
my-linuxbox$ socat TCP4-LISTEN:2560 /dev/ttyUSB0,b115200,raw,echo=0

If you then connect to port 2560 on your computer, everything from there will go to ttyUSB0 and vice versa. Of course only one connection and no other program may use the ttyUSB0 at the same time.
Do not forget the echo=0 otherwise socat will create a loop where it feeds what comes from the CS back to the CS (I don't know why echo=1 is default).
There may be a socat for windows. then it's some COM17 and not /dev/ttyUSB0.

We should document this as a convenient way for folks without a WiFi card where they do have it connected to PC/RPi

**Comment by flash62au** [comment]
I have added a page: https://dcc-ex.com/throttles/connect_wifi_throttle_via_usb.html
And some similar instructions for EX-Toolbox: https://dcc-ex.com/ex-toolbox/using.html#connecting-via-usb

So you can probably close this.
