### ISSUE TITLE
[Documentation Update]: Consolidate "Microcontroller Boards" and "Supported Microcontrollers" pages.

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#782]
### Documentation details

Add UNO R4 and Giga to the "boards that don't work" section possibly. Bullets are showing empty bullets because someone was trying to add space between the entries. It is just confusing that there are 2 places with pretty much the same information and both have to be kept updated. 

See here: https://dcc-ex.com/reference/hardware/microcontroller-boards.html#gsc.tab=0

and here:  https://dcc-ex.com/ex-commandstation/advanced-setup/supported-microcontrollers/index.html#gsc.tab=0

**Comment by peteGSX** [comment]
Now just points to the reference instead, and clarified on Uno R4 + Giga also.
