### ISSUE TITLE
Add Kevin's pin map diagram for Mega

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#81]
Add clickable pins to take you to another page or popup for each pin.
Find where to put this on the web page.

**Comment by Condo-Colin** [comment]
Add a max  Vdc voltage input to the image for 

Arduino USB 5v in
Or use 
Arduino max 7-12Vdc Power in

Plus a
Motor Shield max 12-18Vdc Power in

and add 'output ' or 'out' to  the 3.3 & 5V out pins.

Also Make a separate Mega/Pololu Motor Shield pinout Image for clarification.

**Comment by FrightRisk** [comment]
I have some random notes about pins that I will dump here.
Right now our introduction EX-RAIL Station A & B examples use sensor pin numbers in the 70's.
And mention reserved or dedicated pins for CS Utilities and Expansion on Mega
 0, 1, 4, 10,  {3,12}, {11,13} & 14-19 for Serial ,ETH, StdM/S , WiFi , LCD, HAL, 
& PCA in (SDA, SCL) pins A0,A1 or 20,21 
With STD Motor shield  pins above the following pins either currently reserved for Utilities, or available for either Utilities or Automation
5, 6, 7, 8, 9,  & A2, A3, A4, A5        {please verify}
Alternatively a Pololu Motor shield would utilize pins {7~9} {8~10} from the reserve pins above and free up {3~12} {11~13}
turnouts have their own id space because they are not always related to a pin anyway (eg dcc turnouts)
Later in the more complex expansion diagram show the addition of PCA9685 x n for Servos & Signals Driver/Controller and describing their need at a point where the current draw of the total devices exceeds the total mA the Mega is capable of providing.
Maybe we could assign device ranges by power block district just as an example
 22-29, 30-39, 40 etc (was this done? Fnd)
--------------------
Following Chris' directions above when your making pwm pin choices consider staying as close to what Geoff was using and leave open pins 22-41 for user defined Sensor,Output and Accessory use. And Do Not use pins 50-53 they're special system utility pins Most of our future custom sample EXRAIL accessory projects are go to recommend our Mega users start with pins 22 - 40 for user Dpins and maybe D62-69 aka A6-A15 for their Analog requirements. Leaving D56-D61 akaA2-A5 available for Expansion Motor Board Current Sensing and or shared user open options. If we recommend or help direct our users to general pinout sand boxes to play in it could help gain some uniformity of the client base and generally easier to quickly support call for help
-----------------------
Well, the two pwm (enable) and two dir (signal) pins are definitely used by the shield. Then two analog for current sense are used. Then possibly two brake are connected and pulled low if you have them on your motor shield you can not use them either.
Then some motor shields have connections to A2 and A3 even if they only really use A0 and A1.
Uli — 08/23/2022
I use the standard motor shield Deek-Robot. In this case I can use PIN 2, 4, 5, 6, 7 and 10 (PIN 8 and 9 are for the BrakeA and B),  and the analog pins A2 to A5. Do I need to pay attention to anything with the analog pins or can I just treat them like a digital pin?
Uli — 08/23/2022
So, A4 and A5 are also not usable, because A4 = SCL and A5 = SDA
haba — 08/23/2022
A2 andA3 may be usable depending what exactly your shield connects there.
If you do not use I2C and turn the driver off you should be able to use A4 A5

**Comment by peteGSX** [comment]
This probably has overlaps also: https://github.com/DCC-EX/dcc-ex.github.io/issues/235

**Comment by peteGSX** [comment]
Capturing from old doco project:

Add: Pin usage for motor drivers. The shield uses 3,11,12,13,A0,A1 and will also use the two brake pins 8 and 9 unless the traces are cut.

Beware of pins 50-54 as they have special meaning on a mega. 
Avoid pin 10 as its often used as a chip select

**Comment by peteGSX** [comment]
Covering this as part of https://github.com/DCC-EX/dcc-ex.github.io/issues/390

**Comment by peteGSX** [comment]
Closed by https://github.com/DCC-EX/dcc-ex.github.io/pull/478
