### ISSUE TITLE
[To Do]: Update section on <T> command

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#877]
### Task description

The <T> command was changed and the documentation has not caught up with the changes. We just did not have the memory in a Mega for long lists that could display with a large number of turnouts and their detail of turnout type. We made the decision that if a computer (throttle) was sending commands, IT would know what it was creating and keep track of it itself. For a human operator wanting to debug something, we decided that <T ID X> would be good enough. Updated WEB documentation would probably change that section to this:

<T> lists all defined turnouts in the format <H ID state> 
<T ID X> queries implementation details about turnout ID. Implementation details are shown as ...
(insert current list)

If a throttle needs to know more about the turnouts (if it was DCC, Servo, etc.) it can use the <T> command to get all the turnouts and then query each one in a loop with <T ID X>. An even better idea (from UKBloke) would be to look at the list of defined turnouts in myAutomation.h or wherever you stored the master copy. This will help by including the full description and any hidden turnouts that may have been defined and include any special process that may have been included because the turnout definition is not enough to give all the details.

**Comment by peteGSX** [comment]
The summary already incorporates this change.
