### ISSUE TITLE
[Documentation Update]: Better graphs for the TrackManager waveform explanations

### ISSUE THREAD

**Issue by habazut** [DCC-EX/dcc-ex.github.io#888]
### Documentation details

Exchange Figure 189 Waveform Comparison

### Page with issues

https://dcc-ex.com/trackmanager/index.html#gsc.tab=0

**Comment by habazut** [comment]
[ngspice.zip](https://github.com/DCC-EX/dcc-ex.github.io/files/14936659/ngspice.zip)

**Comment by peteGSX** [comment]
Captured
