### ISSUE TITLE
[Documentation Update]: Version 5.4 Announcement addition

### ISSUE THREAD

**Issue by Kcsmith0708** [DCC-EX/dcc-ex.github.io#894]
### Documentation details

Consider adding at the end of the DCC-EX v5.4 Announcement page a short recap of JMRI feature updates, 
which now includes a new Perform action> 'Open Meters' panel which tracks and displays DCC-EX Current Meter A Main current draw. 

Recap of JMRI v5.7.plus+ ehnancement with DCC-EX v5.4
Requires  Java v11+ and JMRI development v5.7.plus+

In addition to advance JMRI features available to all DCC platforms there are a few more available for DCC-EX.

JMRI new Roster Export to DCC-EX Command Station, a Virtual LCD Display, a updated current meter and more.

   *  'Roster Export to DCC-EX', the ability to press a button and have your complete JMRI Engine Roster shown in a window which you can then copy into your DCC-EX Roster.

This provdes a complete Engine Roster List on your throttles without having to be connected to  a JMRI device.

   *  DCC-EX 'Virtual LCD Displays' on JMRI to see data about your CS and additional user date without having to have physical LCD or OLEDs connected to your command station.

Additional new JMRI DCC-EX  feature improvements;
   * Monitor, Send Command, and Config Base Station now multi-connection-aware.
   * Config Base Station now available as Startup action in Preferences.
   * also a new 'Open Meter' pane in Preferences> Set Up>Add> Perform action> 'Open Meters' 
   * the DCC++ Current Meter now automatically tracks & displays active current draw on Main A
   * new sample script (SendDCCppMessages.py) to easily send DCCpp commmands to run EXRAIL scripts directly from JMRI.
   * new throttles now default to Forward instead of Reverse
   * handle new locoState reply to sync Speed, Dir and F-keys
   * add throttle commands and replies to simulator
   * added support for new servo and vpin turnout messages
   * automatically populate the JMRI Sensor pane by using the new EXRAIL JMRI_SENSOR function.
   * store definitions as properties in created objects
   * Improved CV read speeds by including startVal feature 
   * DCCppOverTCP server now forwards all messages
   *

**Comment by Kcsmith0708** [comment]
Additional Feature updates to the EX v5.4 Announcement

**Comment by peteGSX** [comment]
Captured.
