### ISSUE TITLE
[Documentation Update]: S command shown incorrectly as Z as shown in the details below

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#899]
### Documentation details

![image](https://github.com/DCC-EX/dcc-ex.github.io/assets/37218136/b7ff466b-d0e5-4d78-877c-360c66226855)

### Page with issues

https://dcc-ex.com/ex-commandstation/accessories/sensors/ir-sensor.html#sensor-configuration-for-jmri

**Comment by peteGSX** [comment]
Already fixed in the 5.4.0 release branch... whenever we manage to release that.
