### ISSUE TITLE
Add Ash++'s ESP32 info and comments to the docs.

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#90]
[Ash++ on Discord]https://discord.com/channels/713189617066836079/907288524158558299/929849585151660114

I am now careful to see that I am getting the model that says WROOM-32.  It is the low-cost version and available.
--- ESP32 pins are more scarce than expected; using WiFi may preclude use of all the ADC2 pins and other pins are potentially reserved.  In other words, don't plan on connecting accessories to anything except I2C modules, and use an external transistor/inverter circuit for motor boards.
--- There is a WROOM-32 board in UNO form factor.  It may provide the plug-n-play option with standard motor shield; add jumpers to put current sense pins at A2/A3 locations.  Also 2A is 3.3V, so a question of whether to add voltage divider or zener.  The onboard antenna might be an issue as it is located below the motor shield.
--- Using Arduino IDE for ESP32 is a different experience than with a Mega.  Even after you get the environment installed, it is questionable on whether you have the correct board selected.  And compiling/uploading takes several minutes longer than it does for a Mega. (Or I need a new laptop?)

**Comment by pmantoine** [comment]
NB: the standard Arduino Motor Shield R3 is 3v3 compatible... the LM358 current sensing opamp has its VCC tied to IOREF. This results in an analog signal within the bounds of IOREF, which will be 3v3 on any 3v3 R3 compatible board. This is tested as working for the Sparkfun SAMD21 Dev Breakout board, for instance.

NB: this is NOT the case on most CLONE versions of the Arduino Motor Shield as they appear to have cloned the earlier revisions of it.

**Comment by pmantoine** [comment]
We could have a diagram of how to modify the near-clone motor shields with LM358 opamps - change the input voltage to the opamp to be tied to IOREF rather than straight to +5v as seems common in these designs.
