### ISSUE TITLE
Update EX-RAIL ref page

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#94]
Suggestions & Edits; Sorting EXRAIL Commands  and adding /slash 
from
EXRAIL Functions     Description
<D EXRAIL ON|OFF(addr,subaddr)>
<PAUSE>
<RESUME> 
</> 
</ ROUTES> 
</ START [loco_addr] route_id> 
</ KILL task_id>  
.>/ RESERVE block_id<
</ FREE block_id> 
</ LATCH sensor_id>   
</ UNLATCH sensor_id>  

 
To

EXRAIL Functions     Description
<D EXRAIL ON|OFF(addr,subaddr)>  
</PAUSE>  
</RESUME>  
</ START [loco_addr] route_id> 
</> 
</ KILL task_id> 
</ RESERVE block_id>
</ FREE block_id> 
</ LATCH sensor_id> 
</ UNLATCH sensor_id>
</ ROUTES> //*Under Development with a future JMRI integration release*

add /slash   to /PAUSE & /RESUME
change   from    > RESERVE block_id<  to  <RESERVE block_id>

Also search for and replace  the following;
  'Seria2' with 'Serial2'
  'Disconnect prog track from main'  with 'Disconnect Prog track from Main'
  'command Station'  with  'Command Station'
  'logo'   with  'loco'
  'THROW( id )'  with  'THROW( turnout_id )'

Add to EXRAIL Command References  page missing command
      <D RESET>  Reboot  the Command Station (edited)

**Comment by peteGSX** [comment]
Repurposing this issue to be an overhaul of the pending EX-RAIL command reference page to make sure it is inline with the summary page, with appropriate elaboration of details.

**Comment by peteGSX** [comment]
This will also close https://github.com/DCC-EX/dcc-ex.github.io/issues/188.

**Comment by peteGSX** [comment]
This will also close these:

https://github.com/DCC-EX/dcc-ex.github.io/issues/162
https://github.com/DCC-EX/dcc-ex.github.io/issues/154
https://github.com/DCC-EX/dcc-ex.github.io/issues/105
https://github.com/DCC-EX/dcc-ex.github.io/issues/104
https://github.com/DCC-EX/dcc-ex.github.io/issues/97
