### ISSUE TITLE
Add Ash's resistor pic for LCD brightness.

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#95]
https://dcc-ex.com/reference/hardware/i2c-displays.html#controlling-brightness

**Comment by Condo-Colin** [comment]
![lcd_470R.JPG](https://user-images.githubusercontent.com/85348898/149056518-4691aa26-ea27-4ea5-a057-bff23b698a22.JPG)

**Comment by Condo-Colin** [comment]
from:  NeilMck — 03/01/2021
LCD2004 backlight takes 31mA alone (with built-in series resistor of 100R).   With backlight off it takes 4.8mA. Replaced the jumper with a 470R resistor and total consumption dropped to dropped to 9mA.
LCD is often too bright anyway.

**Comment by ghost** [comment]
Add to that this mention regarding use of I2C LCD display with an ESP or any other 3.3V microcontroller  ( [from ASH++](https://discord.com/channels/713189617066836079/713211119275212842/974123846078713856)): 

> My LCD has the I2C module attached.  SDA/SCL/GND/5V -- the LCD needs 5V, so I remove the pullups when used with ESP32 3.3v.
> Pullups inside red square.
![afbeelding](https://user-images.githubusercontent.com/78744889/168040708-ba361338-2970-4eaa-a1c2-a768f2692c23.png)
