### ISSUE TITLE
Update reference to WiFi preventing broadcast messages

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#99]
https://dcc-ex.com/reference/hardware/wifi-boards.html

Latest version does broadcast sensors and power state but the warning about performance still stands.
Diagnostics are NOT sent over wifi connections  primarily because most of them are for diagnosing wifi problems!

**Comment by FrightRisk** [comment]
Can you make the appropriate changes?
